In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
data={'Name':['Alice','Bob'],'Age':[25,30]}

In [4]:
df=pd.DataFrame(data)

In [5]:
lst=[['Alice',25],['Bob',30]]

In [6]:
df=pd.DataFrame(lst,columns=['Name','Age'])

In [7]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [8]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [10]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [11]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [12]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [13]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [14]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [15]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [16]:
df['Gender']=['F','M']

In [17]:
df.drop('Age',axis=1,inplace=True)

In [18]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [19]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [20]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [21]:
df1=pd.DataFrame({'key':['A','B','C'],'V1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','D'],'V2':[4,5,6]})

In [22]:
pd.merge(df1,df2,on='key')

  key  V1  V2
0   A   1   4
1   B   2   5

In [23]:
pd.merge(df1,df2,on='key')

  key  V1  V2
0   A   1   4
1   B   2   5

In [24]:
df1.join(df2,lsuffix='_left',rsuffix='_right')

  key_left  V1 key_right  V2
0        A   1         A   4
1        B   2         B   5
2        C   3         D   6

In [25]:
import os

In [26]:
os.getcwd()

'C:\\Users\\hp\\OneDrive\\Desktop\\AIML'

In [27]:
df=pd.read_csv('data.csv')

In [28]:
df.to_csv('output.csv',index=False)

In [30]:
df.sort_values('age')

    name  age
0  alice   25
1    bob   30

In [35]:
df['age'].apply(lambda x: x+1)

0    26
1    31
Name: age, dtype: int64

In [38]:
df['name'].unique()

<StringArray>
['alice', 'bob']
Length: 2, dtype: str

In [37]:
df['age'].value_counts()

age
25    1
30    1
Name: count, dtype: int64